### ISSUE TITLE
Need more instructions

### ISSUE THREAD

**Issue by martinhelfrich** [microsoft/crn-engine#14]
I am trying to run any of the projects in the repo. I installed all dependencies but I cannot start / compile anything.

What do I need to do, once I have installed everything?
What should be the startup project?

This projects needs more documentation.

**Comment by ndalchau** [comment]
Hi @martinhelfrich , many thanks for your interest in this project.

Please can you move your efforts to the Fork [here](https://github.com/Biological-Computation/crn-engine)? 

Since all of the original developers of CRN-engine are no longer at Microsoft, the main repo is no longer maintained. Instead, me and my ex-colleagues are maintaining a Fork under our own GitHub organisation. So far, the only differences are really in the _Getting Started_ instructions, but I hope that this will at least partially resolve your questions. If you have further questions, please create an issue in our Fork.

**Comment by martinhelfrich** [comment]
Perfect, thanks for the fast response.
I will check out the Fork.
Maybe one could add a Link to the maintained Repo? Because this Repo is the one that is found by Google.

**Comment by martinhelfrich** [comment]
Nevermind, I found the issue now! Thanks

**Comment by ndalchau** [comment]
Your question had already prompted me to create that other issue. Thanks again!
